# Generated by Django 4.2.13 on 2024-07-24 22:47

import app.fields
import app.models.place
import common.form.img_with_preview
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import map_location.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('center', map_location.fields.LocationField(verbose_name='Zentrum')),
                ('zoom', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(18)], verbose_name='Zoom')),
            ],
            options={
                'verbose_name': 'Stadt',
                'verbose_name_plural': 'Städte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('address', models.CharField(max_length=100, verbose_name='Adresse')),
                ('img', common.form.img_with_preview.ThumbnailImageField(blank=True, null=True, upload_to=app.models.place.overwrite_img_upload, verbose_name='Bild')),
                ('since', app.fields.MonthField(blank=True, max_length=7, null=True, verbose_name='Seit')),
                ('until', app.fields.MonthField(blank=True, max_length=7, null=True, verbose_name='Bis')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('location', map_location.fields.LocationField(blank=True, null=True, verbose_name='Position')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='app.city', verbose_name='Stadt')),
            ],
            options={
                'verbose_name': 'Gebäude',
                'verbose_name_plural': 'Gebäude',
                'ordering': ['address'],
            },
        ),
    ]
