# Generated by Django 4.2.13 on 2024-07-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RunSQL(
            "UPDATE app_place SET img = 'img/'||id||'.jpg' WHERE img != '';"),
    ]
